title: Yasasi Rannulu
 <br><br>
logo: "/images/yaz.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 <br><br>
  **Mobile Application Developer**
  <br><br>
  Co-operative, Out of box thinker experienced in UI /UX, Researching, Testing
  and CI/CD processes in Mobile and Web and Cloud development.
  <br><br>
  
  <a href="https://www.linkedin.com/in/yashrann/">LinkedIn Profile</a> 
 
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
