title: Yasasi Rannulu # your name (or website title) here
logo: "/images/yaz.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Software Engineer 
  <br><br>
  Co-operative, out of box thinker experienced in UI /UX, researching, testing
  and CI/CD processes in mobile / web application, Cloud development.
  <br><br>
  
  <video width="320" height="240" autoplay muted>
  <source src="/images/recyclev.mp4" type="video/mp4">
  
Your browser does not support the video tag.
</video>

  <a href="https://www.linkedin.com/in/yashrann/">LinkedIn Profile</a> 
 

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
